import { useMemo, type ReactNode } from "react";
import { useQuery } from "@tanstack/react-query";
import { CheckCircle2, Clock3, Mail, Plus, Send, Sparkles } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { getMarketingCampaigns } from "@/api/marketing-campaigns";
import { Button } from "@/components/ui/button";

export function MarketingCampaignsLandingPage() {
  const navigate = useNavigate();
  const campaigns = useQuery({ queryKey: ["marketing-campaigns"], queryFn: getMarketingCampaigns });
  const items = campaigns.data ?? [];
  const metrics = useMemo(() => ({ drafts: items.filter((item) => item.status === "DRAFT").length, sent: items.filter((item) => item.status === "SENT").length, recipients: items.reduce((total, item) => total + item.audienceCount, 0) }), [items]);
  const create = () => navigate("/campaigns/new");

  return <div className="space-y-6">
    <section className="rounded-[20px] border border-[#DDEBE2] bg-white px-7 py-7"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#087C48]">Client communications</p><h1 className="mt-2 text-3xl font-extrabold text-[#102E24]">Email campaigns</h1><p className="mt-2 max-w-2xl text-sm text-[#60736B]">Create consent-aware updates, reminders, and offers for Lili Veterinary Hospital clients.</p></div><Button size="lg" onClick={create}><Plus className="h-4 w-4" />Create campaign</Button></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><Metric icon={<Clock3 className="h-5 w-5" />} label="Draft campaigns" value={metrics.drafts} /><Metric icon={<Send className="h-5 w-5" />} label="Sent campaigns" value={metrics.sent} /><Metric icon={<Mail className="h-5 w-5" />} label="Eligible recipients" value={metrics.recipients} /></div></section>
    <section className="rounded-[20px] border border-[#DDEBE2] bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#E5EEE8] px-6 py-5"><div><h2 className="text-xl font-extrabold text-[#102E24]">Your campaigns</h2><p className="mt-1 text-sm text-[#60736B]">Drafts are private until you review and send them.</p></div>{items.length ? <Button variant="outline" onClick={create}><Plus className="h-4 w-4" />New campaign</Button> : null}</div>{campaigns.isLoading ? <p className="p-8 text-sm text-[#60736B]">Loading campaigns...</p> : items.length ? <div className="divide-y divide-[#E5EEE8]">{items.map((campaign) => <button key={campaign.id} type="button" onClick={() => navigate(`/campaigns/${campaign.id}`)} className="flex w-full flex-wrap items-center gap-4 px-6 py-5 text-left transition hover:bg-[#F7FBF8]"><span className={`grid h-10 w-10 place-items-center rounded-full ${campaign.status === "SENT" ? "bg-[#EAF7F0] text-[#087C48]" : "bg-[#F3F6F4] text-[#60736B]"}`}>{campaign.status === "SENT" ? <CheckCircle2 className="h-5 w-5" /> : <Sparkles className="h-5 w-5" />}</span><span className="min-w-52 flex-1"><span className="block font-extrabold text-[#102E24]">{campaign.name}</span><span className="mt-1 block text-sm text-[#60736B]">{campaign.subject || "Subject not added"}</span></span><span className="text-sm text-[#60736B]">{campaign.audienceCount} recipients</span><span className="rounded-full bg-[#F3F6F4] px-3 py-1 text-[10px] font-bold uppercase tracking-wide text-[#60736B]">{campaign.status.replace(/_/g, " ")}</span><span className="text-sm font-bold text-[#087C48]">Open</span></button>)}</div> : <EmptyCampaigns onCreate={create} />}</section>
  </div>;
}

function Metric({ icon, label, value }: { icon: ReactNode; label: string; value: number }) { return <div className="flex items-center gap-3 rounded-xl border border-[#E5EEE8] bg-[#F9FCFA] px-4 py-4"><span className="grid h-9 w-9 place-items-center rounded-full bg-white text-[#087C48]">{icon}</span><span><span className="block text-xl font-extrabold text-[#102E24]">{value}</span><span className="text-xs font-semibold text-[#60736B]">{label}</span></span></div>; }
function EmptyCampaigns({ onCreate }: { onCreate: () => void }) { return <div className="px-6 py-14 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[#EAF7F0] text-[#087C48]"><Mail className="h-6 w-6" /></span><h3 className="mt-4 text-lg font-extrabold text-[#102E24]">No campaigns yet</h3><p className="mx-auto mt-2 max-w-md text-sm text-[#60736B]">Create a campaign, choose recipients, add a subject and design, then review it before delivery.</p><Button className="mt-5" onClick={onCreate}><Plus className="h-4 w-4" />Create your first campaign</Button></div>; }
