import { useEffect, useMemo, useState, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Send, TestTube2, UsersRound } from "lucide-react";
import { createMarketingCampaign, getMarketingCampaigns, sendMarketingCampaign, sendMarketingCampaignTest, updateMarketingCampaign, type CampaignInput } from "@/api/marketing-campaigns";
import { getErrorMessage } from "@/api/http";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/auth/auth-context";
import { isSuperAdmin } from "@/lib/permissions";
import type { MarketingCampaign } from "@/types/api";

const blank: CampaignInput = { name: "", subject: "", previewText: "", htmlContent: "<p>Hello from Lili Veterinary Hospital.</p>", textContent: "Hello from Lili Veterinary Hospital.", contentBlocks: [], recipientSelectionConfirmed: false, designConfigured: false, audienceMode: "CONSENTED_CLIENTS", recipientEmails: [] };

export function MarketingCampaignsPage() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const campaigns = useQuery({ queryKey: ["marketing-campaigns"], queryFn: getMarketingCampaigns });
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [form, setForm] = useState<CampaignInput>(blank);
  const [testEmail, setTestEmail] = useState(user?.email ?? "");
  const [sendConfirmed, setSendConfirmed] = useState(false);
  const selected = useMemo(() => campaigns.data?.find((campaign) => campaign.id === selectedId) ?? null, [campaigns.data, selectedId]);
  const canManage = isSuperAdmin(user);
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["marketing-campaigns"] });
  const save = useMutation({ mutationFn: async () => selected ? updateMarketingCampaign(selected.id, form) : createMarketingCampaign(form), onSuccess: (campaign) => { setSelectedId(campaign.id); setSendConfirmed(false); refresh(); }, onError: (error) => window.alert(getErrorMessage(error, "Could not save campaign.")) });
  const test = useMutation({ mutationFn: () => selected ? sendMarketingCampaignTest(selected.id, testEmail) : Promise.reject(new Error("Save the campaign first")), onSuccess: () => window.alert("Test email sent."), onError: (error) => window.alert(getErrorMessage(error, "Could not send test email.")) });
  const send = useMutation({ mutationFn: () => selected ? sendMarketingCampaign(selected.id) : Promise.reject(new Error("Save the campaign first")), onSuccess: () => { setSendConfirmed(false); refresh(); window.alert("Campaign sent to Brevo for delivery."); }, onError: (error) => window.alert(getErrorMessage(error, "Campaign could not be sent.")) });
  useEffect(() => { if (selected) setForm({ name: selected.name, subject: selected.subject, previewText: selected.previewText ?? "", htmlContent: selected.htmlContent, textContent: selected.textContent, contentBlocks: selected.contentBlocks ?? [], templateId: selected.templateId, recipientSelectionConfirmed: selected.recipientSelectionConfirmed, designConfigured: selected.designConfigured, audienceMode: selected.audienceMode, recipientEmails: selected.customAudience ?? [] }); }, [selected]);

  return <div className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4 rounded-[22px] border border-[#DDEBE2] bg-white px-7 py-6"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#087C48]">Client communications</p><h1 className="mt-2 text-3xl font-extrabold text-[#102E24]">Email campaigns</h1><p className="mt-2 max-w-2xl text-sm text-[#60736B]">Create a compliant campaign for subscribed clients or a Super Admin-selected audience. Opt-outs and suppressions are always excluded.</p></div><UsersRound className="h-10 w-10 text-[#087C48]" /></header>
    <div className="grid gap-6 xl:grid-cols-[310px_minmax(0,1fr)]"><section className="rounded-[20px] border border-[#DDEBE2] bg-white p-5"><Button className="w-full" onClick={() => { setSelectedId(null); setForm(blank); setSendConfirmed(false); }}><Plus className="h-4 w-4" />New campaign</Button><div className="mt-5 space-y-2">{campaigns.isLoading ? <p className="text-sm text-[#60736B]">Loading campaigns...</p> : null}{campaigns.data?.map((campaign) => <button key={campaign.id} type="button" onClick={() => { setSelectedId(campaign.id); setSendConfirmed(false); }} className={`w-full rounded-xl border p-4 text-left ${selectedId === campaign.id ? "border-[#087C48] bg-[#F1F9F4]" : "border-[#DDEBE2] hover:border-[#A8CDBA]"}`}><p className="font-bold text-[#102E24]">{campaign.name}</p><p className="mt-1 text-xs text-[#60736B]">{campaign.audienceCount} eligible clients</p><span className="mt-2 inline-flex rounded-full bg-[#F3F6F4] px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-[#60736B]">{campaign.status.replace(/_/g, " ")}</span></button>)}</div></section>
      <section className="rounded-[20px] border border-[#DDEBE2] bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-extrabold text-[#102E24]">{selected ? selected.name : "New draft"}</h2><p className="mt-1 text-sm text-[#60736B]">The clinic address and Brevo unsubscribe link are added automatically.</p></div>{selected ? <span className="rounded-full bg-[#EAF7F0] px-3 py-1 text-xs font-bold text-[#087C48]">{selected.audienceCount} eligible recipients</span> : null}</div>
        {!canManage ? <p className="mt-6 rounded-lg bg-[#F3F6F4] p-4 text-sm text-[#60736B]">Only a Super Admin can create, test, or send a promotional campaign.</p> : <CampaignEditor form={form} setForm={setForm} onSave={() => save.mutate()} saving={save.isPending} />}
        {selected ? <CampaignActions campaign={selected} testEmail={testEmail} setTestEmail={setTestEmail} onTest={() => test.mutate()} testing={test.isPending} sendConfirmed={sendConfirmed} setSendConfirmed={setSendConfirmed} onSend={() => send.mutate()} sending={send.isPending} canManage={canManage} /> : null}
      </section></div>
  </div>;
}

function CampaignEditor({ form, setForm, onSave, saving }: { form: CampaignInput; setForm: (value: CampaignInput) => void; onSave: () => void; saving: boolean }) {
  const set = <K extends keyof CampaignInput>(key: K, value: CampaignInput[K]) => setForm({ ...form, [key]: value });
  return <div className="mt-6 grid gap-5"><div className="grid gap-4 md:grid-cols-2"><Field label="Campaign name"><Input value={form.name} onChange={(event) => set("name", event.target.value)} placeholder="October dental reminder" /></Field><Field label="Subject line"><Input value={form.subject} onChange={(event) => set("subject", event.target.value)} placeholder="A healthier smile starts here" /></Field></div><Field label="Audience"><select className="h-11 w-full rounded-xl border border-[#DDEBE2] bg-white px-3 text-sm text-[#102E24]" value={form.audienceMode} onChange={(event) => set("audienceMode", event.target.value as CampaignInput["audienceMode"])}><option value="CONSENTED_CLIENTS">Email-marketing subscribers</option><option value="SELECTED_EMAILS">Selected email addresses</option></select></Field>{form.audienceMode === "SELECTED_EMAILS" ? <Field label="Selected email addresses"><textarea className="min-h-28 w-full rounded-xl border border-[#DDEBE2] px-4 py-3 text-sm text-[#102E24] outline-none focus:border-[#087C48]" value={form.recipientEmails.join("\n")} onChange={(event) => set("recipientEmails", event.target.value.split(/[\n,;]+/).map((email) => email.trim()).filter(Boolean))} placeholder="one-email@example.com&#10;another-email@example.com" /><p className="mt-2 text-xs text-[#60736B]">Paste up to 5,000 email addresses. Existing opt-outs and complaints are always excluded.</p></Field> : null}<Field label="Inbox preview"><Input value={form.previewText ?? ""} onChange={(event) => set("previewText", event.target.value)} placeholder="Optional preview text" /></Field><Field label="Email HTML"><textarea className="min-h-48 w-full rounded-xl border border-[#DDEBE2] px-4 py-3 font-mono text-xs text-[#102E24] outline-none focus:border-[#087C48]" value={form.htmlContent} onChange={(event) => set("htmlContent", event.target.value)} /></Field><div className="grid gap-5 lg:grid-cols-2"><Field label="Plain-text version"><textarea className="min-h-32 w-full rounded-xl border border-[#DDEBE2] px-4 py-3 text-sm text-[#102E24] outline-none focus:border-[#087C48]" value={form.textContent} onChange={(event) => set("textContent", event.target.value)} /></Field><div><p className="mb-2 text-xs font-bold uppercase tracking-wide text-[#60736B]">Preview</p><iframe title="Campaign preview" sandbox="" className="h-32 w-full rounded-xl border border-[#DDEBE2] bg-white" srcDoc={form.htmlContent} /></div></div><Button className="w-fit" disabled={saving || !form.name || !form.subject || !form.htmlContent || !form.textContent || (form.audienceMode === "SELECTED_EMAILS" && !form.recipientEmails.length)} onClick={onSave}>{saving ? "Saving" : selectedLabel(form.name)}</Button></div>;
}
function selectedLabel(name: string) { return name ? "Save draft" : "Create draft"; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wide text-[#60736B]">{label}</span>{children}</label>; }
function CampaignActions({ campaign, testEmail, setTestEmail, onTest, testing, sendConfirmed, setSendConfirmed, onSend, sending, canManage }: { campaign: MarketingCampaign; testEmail: string; setTestEmail: (value: string) => void; onTest: () => void; testing: boolean; sendConfirmed: boolean; setSendConfirmed: (value: boolean) => void; onSend: () => void; sending: boolean; canManage: boolean }) {
  if (!canManage || campaign.status !== "DRAFT") return null;
  const audienceLabel = campaign.audienceMode === "SELECTED_EMAILS" ? "the selected addresses" : "email-marketing subscribers";
  return <div className="mt-7 border-t border-[#E5EEE8] pt-6"><h3 className="text-base font-extrabold text-[#102E24]">Review and send</h3><div className="mt-4 flex flex-wrap items-end gap-3"><Field label="Test recipient"><Input className="w-72" type="email" value={testEmail} onChange={(event) => setTestEmail(event.target.value)} /></Field><Button variant="outline" disabled={testing || !testEmail} onClick={onTest}><TestTube2 className="h-4 w-4" />{testing ? "Sending test" : "Send test"}</Button></div><label className="mt-5 flex items-start gap-3 rounded-xl border border-[#DDEBE2] p-4 text-sm text-[#60736B]"><input type="checkbox" checked={sendConfirmed} onChange={(event) => setSendConfirmed(event.target.checked)} className="mt-1" /><span>I confirm this is a promotional email, I have authority to contact {audienceLabel}, and I want Brevo to deliver it to {campaign.audienceCount} eligible recipients. Opt-outs and suppressions remain excluded.</span></label><Button className="mt-4" disabled={!sendConfirmed || sending} onClick={onSend}><Send className="h-4 w-4" />{sending ? "Starting delivery" : "Send campaign"}</Button></div>;
}
